version: '2.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: poc-spring-data-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch

  elasticsearch-hq:
    image: elastichq/elasticsearch-hq:release-v3.5.12
    container_name: poc-spring-data-elasticsearch-hq
    ports:
      - "5000:5000"

volumes:
  elasticsearch-data:
    driver: local

networks:
  elasticsearch:
    driver: bridge